services:
  client:
    build: ./client
    volumes:
      - ./client:/src/page
    ports:
      - "5174:5174"
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    build: ./server
    ports:
      - "5000:5000"
